### ISSUE TITLE
S3 storage cannot store more than 2GB.

### ISSUE THREAD

**Issue by jgoguette** [kestra-io/storage-s3#81]
### Describe the issue

Hello guys running into an issue.
I have an trigger that returned 8 million+ records as it's size.
However, when I run my execution about only 2 million records are being retrieved.
I'm batching the records by 500... so 500 * 3835 amounts to 1917500
Any ideas what could be wrong with my flow/task/trigger that it's not processing all 8 million records?

```
id: tophat2-mysql-connector-9
namespace: namespace

tasks:
  - id: trigger_sub_flow_for_cdc_events
    type: io.kestra.core.tasks.flows.ForEachItem
    items: "{{ trigger.uris['tophat2_staging.roas'] }}"
    batch:
      rows: 500
    namespace: namespace
    flowId: process_cdc_events
    wait: true
    transmitFailed: true
    inputs:
      data: "{{ taskrun.items }}"
      topic: "tophat2_roas"
      

triggers:
  - id: trigger_cdc_events_captured
    type: io.kestra.plugin.debezium.mysql.Trigger
    hostname: hostname
    password: "password"
    username: username
    port: "3306"
    ignoreDdl: true
    maxWait: 3600
    serverId: 9009
    format: INLINE
    snapshotMode: INITIAL
    includedTables:
      - tophat2_staging.roas

disabled: false
```

Docker Compose:
```
volumes:
  kestra-data:
    driver: local

services:
  kestra-webserver:
    image: kestra/kestra:latest-full
    env_file: &env
      - .env_encoded
    pull_policy: always
    restart: "on-failure:30"
    # Note that this is meant for development only. Refer to the documentation for production deployments of Kestra which runs without a root user.
    user: "root"
    command: server standalone --worker-thread=0
    volumes: &volumes
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
    environment: &configuration
      KESTRA_CONFIGURATION: |
        datasources:
          mysql:
            url: url
            driverClassName: com.mysql.cj.jdbc.Driver
            username: username
            password: password
        kestra:
          server:
            basic-auth:
              enabled: true
              username: "username" # it must be a valid email address
              password: password
          repository:
            type: mysql
          storage:
           type: s3
           s3:
             accessKey: "accessKey"
             secretKey: "secretKey"
             region: "region"
             bucket: "bucket"
          queue:
            type: mysql
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
          url: url
          variables:
            globals:
              env: staging
          environment:
            name: Staging
            color: "#FCB37C"
    ports:
      - "80:8080"
      - "8081:8081"

  kestra-worker-1:
    image: kestra/kestra:latest-full
    env_file: *env
    pull_policy: always
    restart: "on-failure:30"
    user: "root"
    command: server worker --thread=128
    volumes: *volumes
    environment: *configuration
    depends_on:
      kestra-webserver:
        condition: service_started
```

<img width="1176" alt="Screenshot 2024-05-07 at 2 17 11 PM" src="https://github.com/kestra-io/kestra/assets/88384557/dff07d2a-c841-46b7-b670-ec2880526473">
<img width="1176" alt="Screenshot 2024-05-07 at 2 17 58 PM" src="https://github.com/kestra-io/kestra/assets/88384557/f50f0f55-8ecc-4010-a076-7b749626107a">

### Environment

- Kestra Version: 0.16.6
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker):
